controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    hexapod_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
hexapod_controller:
  ros__parameters:
    joints:
      - leg_1_coxa_joint
      - leg_2_coxa_joint
      - leg_3_coxa_joint
      - leg_4_coxa_joint
      - leg_5_coxa_joint
      - leg_6_coxa_joint
      - leg_1_tibia_joint
      - leg_2_tibia_joint
      - leg_3_tibia_joint
      - leg_4_tibia_joint
      - leg_5_tibia_joint
      - leg_6_tibia_joint
      - leg_1_femur_joint
      - leg_2_femur_joint
      - leg_3_femur_joint
      - leg_4_femur_joint
      - leg_5_femur_joint
      - leg_6_femur_joint
      
      
      
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    
